/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface XCounter {
    'count': number;
    'maximum': number;
    'minimum': number;
  }
  interface XToggle {
    'checked': boolean;
  }
}

declare global {


  interface HTMLXCounterElement extends Components.XCounter, HTMLStencilElement {}
  var HTMLXCounterElement: {
    prototype: HTMLXCounterElement;
    new (): HTMLXCounterElement;
  };

  interface HTMLXToggleElement extends Components.XToggle, HTMLStencilElement {}
  var HTMLXToggleElement: {
    prototype: HTMLXToggleElement;
    new (): HTMLXToggleElement;
  };
  interface HTMLElementTagNameMap {
    'x-counter': HTMLXCounterElement;
    'x-toggle': HTMLXToggleElement;
  }
}

declare namespace LocalJSX {
  interface XCounter {
    'count'?: number;
    'maximum'?: number;
    'minimum'?: number;
  }
  interface XToggle {
    'checked'?: boolean;
  }

  interface IntrinsicElements {
    'x-counter': XCounter;
    'x-toggle': XToggle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'x-counter': LocalJSX.XCounter & JSXBase.HTMLAttributes<HTMLXCounterElement>;
      'x-toggle': LocalJSX.XToggle & JSXBase.HTMLAttributes<HTMLXToggleElement>;
    }
  }
}


