/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface XToggle {
    'enabled': boolean;
  }
}

declare global {


  interface HTMLXToggleElement extends Components.XToggle, HTMLStencilElement {}
  var HTMLXToggleElement: {
    prototype: HTMLXToggleElement;
    new (): HTMLXToggleElement;
  };
  interface HTMLElementTagNameMap {
    'x-toggle': HTMLXToggleElement;
  }
}

declare namespace LocalJSX {
  interface XToggle {
    'enabled'?: boolean;
  }

  interface IntrinsicElements {
    'x-toggle': XToggle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'x-toggle': LocalJSX.XToggle & JSXBase.HTMLAttributes<HTMLXToggleElement>;
    }
  }
}


